apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: large-disk-nc
spec:
  amiFamily: Bottlerocket
  amiSelectorTerms:
    - alias: bottlerocket@latest
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        encrypted: true
        volumeSize: 50Gi
        volumeType: gp3
    - deviceName: /dev/xvdb
      ebs:
        deleteOnTermination: true
        encrypted: true
        volumeSize: 100Gi
        volumeType: gp3
  metadataOptions:
    httpPutResponseHopLimit: 2
  role: staging-eks-karpenter-node
  securityGroupSelectorTerms:
    - tags:
        Name: staging-eks-node
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: staging-eks
  tags:
    Environment: staging
    Name: staging-karpenter-node-large-disk
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: large-disk-np
spec:
  disruption:
    consolidateAfter: 12h
    consolidationPolicy: WhenEmptyOrUnderutilized
  limits:
    cpu: 60
    memory: 200Gi
  template:
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: large-disk-nc
      requirements:
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["t", "m", "c", "r"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["2xlarge", "4xlarge"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
        - key: karpenter.k8s.aws/instance-hypervisor
          operator: In
          values: ["nitro"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
