name: Package and Push Helm Charts

'on':
  push:
    branches: [stacklok-main, main]
    paths:
      - 'deployment/helm/charts/onyx/**'
      - '.github/workflows/package-push-helm-charts.yml'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 781189302813.dkr.ecr.us-east-1.amazonaws.com

permissions:
  contents: read
  id-token: write

jobs:
  package-and-push-helm-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq

      - name: Add Helm repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add vespa https://onyx-dot-app.github.io/vespa-helm-charts
          helm repo update

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::781189302813:role/github-actions-research
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.3'

      - name: Package Helm Charts
        run: |
          # Debug: Show current directory
          pwd
          echo "Directory contents before packaging:"
          ls -la

          # Package Onyx chart
          echo "Packaging Onyx chart..."
          helm dependency update deployment/helm/charts/onyx
          helm package deployment/helm/charts/onyx
          
          # Verify Onyx chart was created
          if [ ! -f onyx-stack-*.tgz ]; then
            echo "Error: Onyx chart package was not created"
            exit 1
          fi

          echo "Directory contents after packaging:"
          ls -la *.tgz

      - name: Push Helm Charts to ECR
        run: |
          # Login to ECR
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
            helm registry login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

          # Push Onyx chart
          echo "Pushing Onyx chart..."
          ONYX_CHART=$(ls onyx-stack-*.tgz 2>/dev/null || true)
          if [ -z "$ONYX_CHART" ]; then
            echo "Error: Onyx chart package not found in root directory"
            echo "Current directory contents:"
            ls -la
            exit 1
          fi
          echo "Found chart: $ONYX_CHART"
          helm push "$ONYX_CHART" "oci://${{ env.ECR_REGISTRY }}"
